package model;
// Generated 2020�~11��12�� �U��2:33:09 by Hibernate Tools 5.4.21.Final

/**
 * Suppliers generated by hbm2java
 */
public class Suppliers implements java.io.Serializable {

	private int id;
	private String companyname;
	private String address;
	private String email;
	private String phone;
	private String salesName;
	private String salesPhone;
	private String salesEmail;

	public Suppliers() {
	}

	public Suppliers(int id) {
		this.id = id;
	}

	public Suppliers(int id, String companyname, String address, String email, String phone, String salesName,
			String salesPhone, String salesEmail) {
		this.id = id;
		this.companyname = companyname;
		this.address = address;
		this.email = email;
		this.phone = phone;
		this.salesName = salesName;
		this.salesPhone = salesPhone;
		this.salesEmail = salesEmail;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCompanyname() {
		return this.companyname;
	}

	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getSalesName() {
		return this.salesName;
	}

	public void setSalesName(String salesName) {
		this.salesName = salesName;
	}

	public String getSalesPhone() {
		return this.salesPhone;
	}

	public void setSalesPhone(String salesPhone) {
		this.salesPhone = salesPhone;
	}

	public String getSalesEmail() {
		return this.salesEmail;
	}

	public void setSalesEmail(String salesEmail) {
		this.salesEmail = salesEmail;
	}

}
